name: Docker Image CI

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  deployments:
    runs-on: ubuntu-latest
    steps:
      - name: login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: maranathachristianuniversity
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - name: create image from repository
        run: docker build -t ghcr.io/maranathachristianuniversity/status-api .
      - name: push image to GitHub Container Registry
        run: docker push ghcr.io/maranathachristianuniversity/status-api:latest

